// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID           pgtype.UUID
	State        int16
	CreatedAt    pgtype.Timestamp
	MessageTopic pgtype.Text
	MessageKey   []byte
	MessageBody  []byte
}
