// Code generated by http://github.com/gojuno/minimock (v3.3.13). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/usecase/order.Publisher -o publisher_mock.go -n PublisherMock -p mock

import (
	"context"
	"route256/transactionalbox/pkg/transactionalbox"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PublisherMock implements order.Publisher
type PublisherMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSend          func(ctx context.Context, msg transactionalbox.Message) (err error)
	inspectFuncSend   func(ctx context.Context, msg transactionalbox.Message)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mPublisherMockSend
}

// NewPublisherMock returns a mock for order.Publisher
func NewPublisherMock(t minimock.Tester) *PublisherMock {
	m := &PublisherMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mPublisherMockSend{mock: m}
	m.SendMock.callArgs = []*PublisherMockSendParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPublisherMockSend struct {
	optional           bool
	mock               *PublisherMock
	defaultExpectation *PublisherMockSendExpectation
	expectations       []*PublisherMockSendExpectation

	callArgs []*PublisherMockSendParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// PublisherMockSendExpectation specifies expectation struct of the Publisher.Send
type PublisherMockSendExpectation struct {
	mock      *PublisherMock
	params    *PublisherMockSendParams
	paramPtrs *PublisherMockSendParamPtrs
	results   *PublisherMockSendResults
	Counter   uint64
}

// PublisherMockSendParams contains parameters of the Publisher.Send
type PublisherMockSendParams struct {
	ctx context.Context
	msg transactionalbox.Message
}

// PublisherMockSendParamPtrs contains pointers to parameters of the Publisher.Send
type PublisherMockSendParamPtrs struct {
	ctx *context.Context
	msg *transactionalbox.Message
}

// PublisherMockSendResults contains results of the Publisher.Send
type PublisherMockSendResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSend *mPublisherMockSend) Optional() *mPublisherMockSend {
	mmSend.optional = true
	return mmSend
}

// Expect sets up expected params for Publisher.Send
func (mmSend *mPublisherMockSend) Expect(ctx context.Context, msg transactionalbox.Message) *mPublisherMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &PublisherMockSendExpectation{}
	}

	if mmSend.defaultExpectation.paramPtrs != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by ExpectParams functions")
	}

	mmSend.defaultExpectation.params = &PublisherMockSendParams{ctx, msg}
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// ExpectCtxParam1 sets up expected param ctx for Publisher.Send
func (mmSend *mPublisherMockSend) ExpectCtxParam1(ctx context.Context) *mPublisherMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &PublisherMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &PublisherMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.ctx = &ctx

	return mmSend
}

// ExpectMsgParam2 sets up expected param msg for Publisher.Send
func (mmSend *mPublisherMockSend) ExpectMsgParam2(msg transactionalbox.Message) *mPublisherMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &PublisherMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &PublisherMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.msg = &msg

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the Publisher.Send
func (mmSend *mPublisherMockSend) Inspect(f func(ctx context.Context, msg transactionalbox.Message)) *mPublisherMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for PublisherMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by Publisher.Send
func (mmSend *mPublisherMockSend) Return(err error) *PublisherMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &PublisherMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &PublisherMockSendResults{err}
	return mmSend.mock
}

// Set uses given function f to mock the Publisher.Send method
func (mmSend *mPublisherMockSend) Set(f func(ctx context.Context, msg transactionalbox.Message) (err error)) *PublisherMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the Publisher.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the Publisher.Send method")
	}

	mmSend.mock.funcSend = f
	return mmSend.mock
}

// When sets expectation for the Publisher.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mPublisherMockSend) When(ctx context.Context, msg transactionalbox.Message) *PublisherMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("PublisherMock.Send mock is already set by Set")
	}

	expectation := &PublisherMockSendExpectation{
		mock:   mmSend.mock,
		params: &PublisherMockSendParams{ctx, msg},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up Publisher.Send return parameters for the expectation previously defined by the When method
func (e *PublisherMockSendExpectation) Then(err error) *PublisherMock {
	e.results = &PublisherMockSendResults{err}
	return e.mock
}

// Times sets number of times Publisher.Send should be invoked
func (mmSend *mPublisherMockSend) Times(n uint64) *mPublisherMockSend {
	if n == 0 {
		mmSend.mock.t.Fatalf("Times of PublisherMock.Send mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSend.expectedInvocations, n)
	return mmSend
}

func (mmSend *mPublisherMockSend) invocationsDone() bool {
	if len(mmSend.expectations) == 0 && mmSend.defaultExpectation == nil && mmSend.mock.funcSend == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSend.mock.afterSendCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSend.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Send implements order.Publisher
func (mmSend *PublisherMock) Send(ctx context.Context, msg transactionalbox.Message) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(ctx, msg)
	}

	mm_params := PublisherMockSendParams{ctx, msg}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, &mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_want_ptrs := mmSend.SendMock.defaultExpectation.paramPtrs

		mm_got := PublisherMockSendParams{ctx, msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSend.t.Errorf("PublisherMock.Send got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmSend.t.Errorf("PublisherMock.Send got unexpected parameter msg, want: %#v, got: %#v%s\n", *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("PublisherMock.Send got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the PublisherMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(ctx, msg)
	}
	mmSend.t.Fatalf("Unexpected call to PublisherMock.Send. %v %v", ctx, msg)
	return
}

// SendAfterCounter returns a count of finished PublisherMock.Send invocations
func (mmSend *PublisherMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of PublisherMock.Send invocations
func (mmSend *PublisherMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to PublisherMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mPublisherMockSend) Calls() []*PublisherMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*PublisherMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *PublisherMock) MinimockSendDone() bool {
	if m.SendMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMock.invocationsDone()
}

// MinimockSendInspect logs each unmet expectation
func (m *PublisherMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PublisherMock.Send with params: %#v", *e.params)
		}
	}

	afterSendCounter := mm_atomic.LoadUint64(&m.afterSendCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && afterSendCounter < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to PublisherMock.Send")
		} else {
			m.t.Errorf("Expected call to PublisherMock.Send with params: %#v", *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && afterSendCounter < 1 {
		m.t.Error("Expected call to PublisherMock.Send")
	}

	if !m.SendMock.invocationsDone() && afterSendCounter > 0 {
		m.t.Errorf("Expected %d calls to PublisherMock.Send but found %d calls",
			mm_atomic.LoadUint64(&m.SendMock.expectedInvocations), afterSendCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PublisherMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PublisherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PublisherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
